sudo: required
language: generic

services: 
  - docker

  before_install:
  - docker build -t nathanielgreenwood/demo-react-app -f Dockerfile.dev . 
  

  script:
  - docker run -e CI=true nathanielgreenwood/demo-react-app npm run test

  