sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t nathanielgreenwood/demo-react-app -f Dockerfile.dev . 

script:
  - docker run -e CI=true nathanielgreenwood/demo-react-app npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "demo-react-app"
  env: "Demoreactapp-env"
  bucket_name: "elasticbeanstalk-eu-west-1-294098874112"
  bucket_path: "demo-react-app"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY